/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

/**
 *
 * @author 
 * Nama : Yasmina Syahidah
 * NIM : 24060124130116
 */

import javax.swing.*;
import java.util.*;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;
public class JFrameUtama extends javax.swing.JFrame {
    DefaultListModel<String> dlmNama; 
    DefaultListModel<String> dlmId; 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());

    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        this.dlmNama = new DefaultListModel<>();
         this.dlmId = new DefaultListModel<>();
         this.jListNama.setModel(dlmNama);
         this.jListId.setModel(dlmId);
          jListId.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int index = jListId.getSelectedIndex();
            if (index >= 0) {
                // Isi textfield ID dan Nama di bagian Edit
                jTextFieldIDEdit.setText(dlmId.getElementAt(index));
                jTextFieldNamaEdit.setText(dlmNama.getElementAt(index));
                
                // Isi textfield ID dan Nama di bagian Hapus
                jTextFieldIDDelete.setText(dlmId.getElementAt(index));
                jTextFieldNamaDelete.setText(dlmNama.getElementAt(index));
            }
        }
        });
    }
    
    private void addItem(int id, String namaItem){
        dlmNama.addElement(namaItem);
        dlmId.addElement(String.valueOf(id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListId = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jButtonSelectAll = new javax.swing.JButton();
        jTextFieldNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldIDEdit = new javax.swing.JTextField();
        jTextFieldNamaEdit = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jTextFieldNamaDelete = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldIDDelete = new javax.swing.JTextField();
        jButtonResetIndeks = new javax.swing.JButton();
        jLabelReset = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListId.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListId);

        jListNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListNama);

        jButtonSelectAll.setText("Ambil semua data");
        jButtonSelectAll.addActionListener(this::jButtonSelectAllActionPerformed);

        jTextFieldNama.addActionListener(this::jTextFieldNamaActionPerformed);

        jLabel1.setText("nama :");

        jButtonAdd.setText("add");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jTextFieldNamaEdit.addActionListener(this::jTextFieldNamaEditActionPerformed);

        jButtonEdit.setText("edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonDelete.setText("delete");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonResetIndeks.setText("Reset Indeks");
        jButtonResetIndeks.addActionListener(this::jButtonResetIndeksActionPerformed);

        jLabelReset.setText("Indeks di reset ke 0");

        jLabel2.setText("Kelola Data Mahasiswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNama)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSelectAll)
                            .addComponent(jButtonAdd)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEdit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNamaDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonResetIndeks)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelReset))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(jButtonSelectAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonResetIndeks)
                            .addComponent(jLabelReset)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jTextFieldNamaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaEditActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTextFieldNamaEditActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        int index = jListId.getSelectedIndex();
        String namaBaru = jTextFieldNamaEdit.getText().trim();
        int id = Integer.parseInt(dlmId.getElementAt(index));
        MysqlMahasiswaService service = new MysqlMahasiswaService();
        Mahasiswa mhs = service.makeMhsObject();
        mhs.setId(id);
        mhs.setNama(namaBaru);
        service.update(mhs);
        dlmNama.setElementAt(namaBaru, index);
          jTextFieldIDEdit.setText("");
            jTextFieldNamaEdit.setText("");
                
              
            jTextFieldIDDelete.setText("");
            jTextFieldNamaDelete.setText("");
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectAllActionPerformed
        // TODO add your handling code here:
        dlmId.clear();
        dlmNama.clear();
      MysqlMahasiswaService service = new MysqlMahasiswaService();
      List<Mahasiswa> list = service.getAll();
       for (Mahasiswa m : list) {
        addItem(m.getId(), m.getNama());}
    }//GEN-LAST:event_jButtonSelectAllActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int index = jListId.getSelectedIndex();
        int id = Integer.parseInt(dlmId.getElementAt(index));
        MysqlMahasiswaService service = new MysqlMahasiswaService();
         service.delete(id);
         dlmNama.removeElementAt(index);
         dlmId.removeElementAt(index);
         
                jTextFieldIDEdit.setText("");
                jTextFieldNamaEdit.setText("");
                
                
                jTextFieldIDDelete.setText("");
                jTextFieldNamaDelete.setText("");
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonResetIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetIndeksActionPerformed
        // TODO add your handling code here:
        MysqlMahasiswaService service = new MysqlMahasiswaService();
       
        if(service.isEmpty()) {
            service.indexReset();
            jLabelReset.setText("Index di reset ke 1");
        }else {
            JOptionPane.showMessageDialog(this,
            "Tabel tidak kosong!\nHapus semua data.",
            "Peringatan", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_jButtonResetIndeksActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String nama = jTextFieldNama.getText().trim();
        MysqlMahasiswaService service = new MysqlMahasiswaService();
        Mahasiswa mhs = service.makeMhsObject();
        mhs.setNama(nama);
        service.add(mhs);
        List<Mahasiswa> list = service.getAll();
        addItem(list.get(list.size()-1).getId(), nama);
        jTextFieldNama.setText("");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonResetIndeks;
    private javax.swing.JButton jButtonSelectAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelReset;
    private javax.swing.JList<String> jListId;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldIDDelete;
    private javax.swing.JTextField jTextFieldIDEdit;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNamaDelete;
    private javax.swing.JTextField jTextFieldNamaEdit;
    // End of variables declaration//GEN-END:variables
}
